# Generated by Django 4.0.4 on 2022-08-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ke', models.CharField(max_length=6)),
                ('j', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=20)),
                ('question1', models.CharField(max_length=20)),
                ('question2', models.CharField(max_length=20)),
                ('question3', models.CharField(max_length=20)),
                ('question4', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=10)),
            ],
        ),
    ]
