# Generated by Django 4.0.4 on 2022-08-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_key_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='j',
        ),
    ]
