# Generated by Django 4.0.4 on 2022-08-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_key_j'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='j',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
