# Generated by Django 4.0.4 on 2022-08-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_key_j'),
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('participated', models.CharField(max_length=10)),
            ],
        ),
    ]
