# Generated by Django 4.0.4 on 2022-09-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_rename_s_score_se'),
    ]

    operations = [
        migrations.CreateModel(
            name='teach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dept_id', models.CharField(max_length=13)),
                ('email_id', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
    ]
