# Generated by Django 4.0.4 on 2022-09-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_teach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='ke',
        ),
        migrations.AddField(
            model_name='key',
            name='branch',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='mid',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='regulation',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='key',
            name='subject',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
