# Generated by Django 4.0.4 on 2022-09-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_remove_key_ke_key_branch_key_mid_key_regulation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teach',
            old_name='branch',
            new_name='dept_roll_id',
        ),
        migrations.RenameField(
            model_name='teach',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='teach',
            name='dept_id',
        ),
        migrations.AddField(
            model_name='regis',
            name='BRANCH',
            field=models.CharField(choices=[('CSE', 'COMPUTER SCIENCE AND ENGINEERING'), ('CIV', 'CIVIL ENGINEERING'), ('MECH', 'MECHANICAL ENGINEERING'), ('ECE', 'ELECTRONICS AND COMMUNICATION ENGINEERING'), ('EEE', 'ELECTRICAL AND ELECTRONIC ENGINEERING')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regis',
            name='regulation',
            field=models.CharField(choices=[('r19', 'r19'), ('r20', 'r20'), ('r21', 'r21'), ('r22', 'r22')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regis',
            name='rollno',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regis',
            name='year',
            field=models.CharField(choices=[('I', 'I ST YEAR'), ('II', 'II ND YEAR'), ('III', 'III RD YEAR'), ('IV', 'IV TH YEAR')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teach',
            name='dept',
            field=models.CharField(choices=[('CSE', 'COMPUTER SCIENCE AND ENGINEERING'), ('CIV', 'CIVIL ENGINEERING'), ('MECH', 'MECHANICAL ENGINEERING'), ('ECE', 'ELECTRONICS AND COMMUNICATION ENGINEERING'), ('EEE', 'ELECTRICAL AND ELECTRONIC ENGINEERING')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teach',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
