# Generated by Django 4.0.4 on 2022-09-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='question',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
