# Generated by Django 4.0.4 on 2022-09-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
