# Generated by Django 4.0.4 on 2022-09-30 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_alter_form_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Form',
        ),
    ]
