# Generated by Django 4.0.4 on 2022-10-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='teacher',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
