# Generated by Django 4.0.4 on 2022-10-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_form_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='student',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
